### ISSUE TITLE
RF12 RoadMap (Jeelib)

### ISSUE THREAD

**Issue by TheDistractor** [jcw/jeelib#61]
OK, its just a start as I have no idea where its going....;)
If we update this top item, we can at least keep the milestones visible at top of thread and further discussion can support the RoadMap. Please keep side-discussions somewhere else so this thread stays concise.

About: To discuss and identify some 'roadmap/milestone' items for the RF12 specific parts of the jeelib library - feel free to clarify the task lists until we reach a good point.

RF12 Versions
- [ ] clarify versions for driver / utilities (and be able to retrieve from github)

One we know starting point we can agree a new release version
i.e RF12Driver next release will be at v3
     RFDemo next release at v12

The next agreed release will have??:

RF12 Config
- [ ] New EEPROM config structure
- [ ] New config string reported (format: ???????????????)

RF12 Tuning
- [ ] Short Writeup.
- [ ] Core Tuning features added to Driver.
- [ ] Core Tuning features added to RF12Demo and support scripts

RF12 Node Discovery
- [ ] Short Writeup 
- [ ] ??

RF12 Remote script uploading
- [ ] Short Writeup
- [ ] ??

RF12 Feature Selection (so smaller cores like T84 can optionally include) 
- [ ] Feature 1 (all cores)
- [ ] Feature 2 (excluded on T84 by default)
- [ ] Feature 3 (not supported on T84)

etc - I'll come back and tidy this up in a few hours
